### PR TITLE
Added N-Form Probe

### PR DESCRIPTION
**Pull request by theilmbh**
Added port list for N-Form probe in probe dictionary.

### CODE REVIEW

**Comment by neuromusic** [comment]
do you want to add an N-form probe file before I merge this? else the script will bork at line 146 when it tries to copy it over.

or we edit that line to catch the error when it can't find the probe file and remind the user that they will need to manually copy a probe file over

**Comment by theilmbh** [comment]
Yep, we have a probe file.  I'll commit that shortly


On Wed, Apr 1, 2015 at 5:08 PM, Justin Kiggins <notifications@github.com>
wrote:

> do you want to add an N-form probe file before I merge this? else the
> script will bork at line 146 when it tries to copy it over.
>
> or we edit that line to catch the error when it can't find the probe file
> and remind the user that they will need to manually copy a probe file over
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gentnerlab/glab-common-py/pull/5#issuecomment-88671817>
> .
>



-- 
Brad Theilman
University of California, San Diego
btheilman@ucsd.edu <theilmbh@mail.uc.edu>
bradtheilman@gmail.com

**Comment by neuromusic** [comment]
cool. just lemme know when its ready

**Comment by MarvinT** [comment]
should be moved to klusta pipeline

**Pull request closed without merging**
